// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvrz-m1FEa_EFtuGr3CBzTnAqxp_gii4M',
    appId: '1:636245305736:web:094a5d0594b406d897b23d',
    messagingSenderId: '636245305736',
    projectId: 'library-5bc5f',
    authDomain: 'library-5bc5f.firebaseapp.com',
    storageBucket: 'library-5bc5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCQsWI0CcJeF7kZKqpFZekaKnv28oiqAY',
    appId: '1:636245305736:android:ed7c5ed86585a42297b23d',
    messagingSenderId: '636245305736',
    projectId: 'library-5bc5f',
    storageBucket: 'library-5bc5f.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvrz-m1FEa_EFtuGr3CBzTnAqxp_gii4M',
    appId: '1:636245305736:web:5e8f28e74dcc46e197b23d',
    messagingSenderId: '636245305736',
    projectId: 'library-5bc5f',
    authDomain: 'library-5bc5f.firebaseapp.com',
    storageBucket: 'library-5bc5f.appspot.com',
  );

}